package:
  name: newspaper
  version: !!str 0.0.7

source:
  fn: newspaper-0.0.7.tar.gz
  url: https://pypi.python.org/packages/source/n/newspaper/newspaper-0.0.7.tar.gz
  md5: 4fd2796ec97610bf99bde8de6dfd337e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - newspaper = newspaper:main
    #
    # Would create an entry point called newspaper that calls newspaper.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - lxml
    - requests
    - nltk
    - pillow
    - cssselect
    - beautifulsoup

  run:
    - python
    - lxml
    - requests
    - nltk
    - pillow
    - cssselect
    - beautifulsoup

test:
  # Python imports
  imports:
    - newspaper
    - newspaper.data
    - newspaper.packages
    - newspaper.packages.feedparser
    - newspaper.packages.jieba
    - newspaper.packages.jieba.analyse
    - newspaper.packages.jieba.finalseg
    - newspaper.packages.jieba.posseg
    - newspaper.packages.tldextract

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/codelucas/newspaper/
  license: mit
  summary: 'Simplified python article discovery & extraction.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
